---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - name: Install flashplayer
    win_chocolatey:
      name: flashplayerppapi
      state: present
    notify:
    - reboot server
  - name: Failing the task
    debug:
      msg: Test failing the task
    failed_when: true
  - name: This is another task
    debug:
      msg: final task
  handlers:
  - name: reboot server
    win_reboot: