---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install VLC
    win_chocolatey:
      name: vlc
      state: present
    notify:
    - reboot server
  - name: Failing the task
    fail:
      msg: Test failing the task
  handlers:
  - name: reboot server
    win_reboot: