---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install 7zip
    win_chocolatey:
      name: 7zip
      state: present
    notify:
    - reboot server
  - name: Failing the task
    debug:
      msg: Test failing the task
    failed_when: true
  - name: This is another task
    debug:
      msg: final task
  handlers:
  - name: reboot server
    win_reboot: