---
- name: Testing Powershell
  hosts: all
  gather_facts: false
  tasks:
  - name: Get services
    win_shell: |
      Get-Service | fl Name,DisplayName,Status
  #   register: output
  # - debug:
  #     var: output