---
- name: Testing Powershell
  hosts: all
  gather_facts: false
  tasks:
  - name: Get services
    win_command:
      name: powershell.exe
      args: get-service
    register: output
  - debug:
      var: output